(() => {
  "use strict";
  const $ = q => document.querySelector(q);
  const esc = value => { const e=document.createElement("span");e.textContent=value??"";return e.innerHTML; };
  let side = 0;
  const positionLabel = value => value || "－";
  function inningRuns(state, team, inning){return (state.runEvents||[]).filter(run=>run.inning===inning&&((run.half==="top"?0:1)===team)).length;}
  function symbolInfo(pa){
    if(!pa)return {mark:"",advance:0,pitches:[],out:""};
    const s=pa.score||{};const result=s.result||pa.text||"";const fielders=s.fielders||[];const seq=fielders.join("-");let mark="",advance=0;
    const batted=({ゴロ:"∪",ライナー:"－",フライ:"∩",バント:"BT"})[s.contact]||"";
    if(result==="四球"){mark="B";advance=1;}else if(result==="死球"){mark="DB";advance=1;}else if(result==="strikeout"||result==="三振"){mark="K";}else if(result==="振り逃げ"){mark="ꓘ";advance=(s.decisions||[]).some(d=>d.runner==="batter"&&d.result==="SAFE")?1:0;}else if(result==="単打"){mark=`${fielders[0]||""}${batted||"∪"}`;advance=1;}else if(result==="二塁打"){mark=`${fielders[0]||""}${batted||"－"}②`;advance=2;}else if(result==="三塁打"){mark=`${fielders[0]||""}${batted||"－"}③`;advance=3;}else if(result==="本塁打"){mark=`${fielders[0]||""}${batted||"∩"}HR`;advance=4;}else if(result==="野選"){mark=`FC ${seq}`;advance=1;}else if(/エラー/.test(result)){mark=`${fielders.at(-1)||fielders[0]||""}E`;advance=1;}else if(result==="犠打"){mark=`◇${seq||"BT"}`;}else if(result==="犠飛"){mark=`◇${fielders[0]||""}∩`;}else if(result==="バントアウト"){mark=`BT ${seq}`;}else if(result==="catch"){mark=`${fielders[0]||""}${s.contact==="ライナー"?"－":"∩"}`;}else if(seq){mark=`${seq}${batted}`;}else{
      const old=String(pa.text||"");if(old==="三振")mark="K";else if(old==="四球"){mark="B";advance=1;}else if(old==="死球"){mark="DB";advance=1;}else if(/本$/.test(old)){mark="HR";advance=4;}else if(/3$/.test(old)){mark="③";advance=3;}else if(/2$/.test(old)){mark="②";advance=2;}else if(/安$/.test(old)){mark="∪";advance=1;}else if(/失$/.test(old)){mark="E";advance=1;}else if(/野選$/.test(old)){mark="FC";advance=1;}else if(/直$/.test(old))mark="－";else if(/飛$/.test(old))mark="∩";else mark=old;
    }
    return {mark,advance,pitches:s.pitches||[],out:({1:"Ⅰ",2:"Ⅱ",3:"Ⅲ"})[s.outNumber]||"",run:advance===4};
  }
  function symbolCell(pa){const info=symbolInfo(pa);if(!pa)return "";const pts=[[35,53],[58,31],[35,9],[12,31],[35,53]];const lines=Array.from({length:Math.min(4,info.advance)},(_,i)=>`<line x1="${pts[i][0]}" y1="${pts[i][1]}" x2="${pts[i+1][0]}" y2="${pts[i+1][1]}"/>`).join("");return `<svg class="score-symbol" viewBox="0 0 70 62" role="img" aria-label="${esc(pa.text||info.mark)}"><path class="diamond" d="M35 9 L58 31 L35 53 L12 31 Z"/><g class="advance ${info.advance?"reached":""}">${lines}</g><text class="pitch-seq" x="3" y="8">${esc(info.pitches.join(""))}</text><text class="play-mark" x="35" y="35">${esc(info.mark)}</text><text class="out-mark" x="35" y="50">${esc(info.out)}</text>${info.run?'<circle class="run-mark" cx="35" cy="31" r="17"/>':""}</svg>`;}
  function buildSheet(){
    const state=window.ScorebookGame?.snapshot();if(!state)return;
    const team=state.teams[side]||{name:side?"後攻":"先攻"};const opponent=state.teams[1-side]||{};
    const innings=Math.max(9,state.inning||1);const inningHeaders=Array.from({length:innings},(_,i)=>`<th>${i+1}</th>`).join("");
    const scoreRows=[0,1].map(teamIndex=>`<tr><th>${esc(state.teams[teamIndex]?.name||["先攻","後攻"][teamIndex])}</th>${Array.from({length:innings},(_,i)=>`<td>${inningRuns(state,teamIndex,i+1)||""}</td>`).join("")}<td class="total">${state.scores[teamIndex]}</td></tr>`).join("");
    const rows=state.lineupSlots[side].map((slot,i)=>{const player=state.players.find(p=>p.id===slot.currentPlayerId)||{};const appearance=[...(state.appearances||[])].reverse().find(a=>a.playerId===slot.currentPlayerId);const pa=state.plateAppearances[side][i]||[];return `<tr><th>${i+1}</th><td>${esc(player.uniformNumber||"")}</td><td class="player">${esc(player.canonicalName||"")}</td><td>${esc(positionLabel(appearance?.defensiveNumber||appearance?.defensivePositions?.at(-1)))}</td>${Array.from({length:9},(_,j)=>`<td class="pa">${symbolCell(pa[j])}</td>`).join("")}</tr>`;}).join("");
    $("#scorebookSideLabel").textContent=side===0?"先攻":"後攻";$("#toggleScorebookSide").textContent=side===0?"後攻へ":"先攻へ";
    $("#scorebookSheet").innerHTML=`<div class="scorebook-title"><span>${esc(team.name)}</span><h2>試合スコアブック</h2><span class="score">${state.scores[0]} － ${state.scores[1]}</span></div><table class="score-line"><thead><tr><th>チーム</th>${inningHeaders}<th>計</th></tr></thead><tbody>${scoreRows}</tbody></table><table class="score-grid"><thead><tr><th>打順</th><th>背番号</th><th>選手名</th><th>守備</th>${Array.from({length:9},(_,i)=>`<th>打席${i+1}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><p class="scorebook-note">表示：${esc(team.name)}　対戦：${esc(opponent.name||"")}　最終更新：${new Date().toLocaleString("ja-JP")}</p>`;
  }
  function drawExport(canvas,state){
    const ctx=canvas.getContext("2d");const W=1600,H=900;canvas.width=W;canvas.height=H;ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#173424";ctx.font="bold 34px sans-serif";ctx.textAlign="center";ctx.fillText("試合スコアブック",W/2,48);ctx.font="bold 25px sans-serif";ctx.textAlign="left";ctx.fillText(state.teams[side]?.name||["先攻","後攻"][side],40,88);ctx.textAlign="right";ctx.fillText(`${state.scores[0]} － ${state.scores[1]}`,W-40,88);
    const x0=35,y0=115,rowH=68,widths=[60,80,210,80,...Array(9).fill(124)];const headers=["打順","背番号","選手名","守備",...Array.from({length:9},(_,i)=>`打席${i+1}`)];ctx.strokeStyle="#20382b";ctx.lineWidth=2;ctx.font="bold 18px sans-serif";ctx.textAlign="center";let x=x0;headers.forEach((h,i)=>{ctx.strokeRect(x,y0,widths[i],rowH);ctx.fillText(h,x+widths[i]/2,y0+41);x+=widths[i];});
    state.lineupSlots[side].forEach((slot,row)=>{const player=state.players.find(p=>p.id===slot.currentPlayerId)||{};const appearance=[...(state.appearances||[])].reverse().find(a=>a.playerId===slot.currentPlayerId);const basics=[row+1,player.uniformNumber||"",player.canonicalName||"",appearance?.defensiveNumber||appearance?.defensivePositions?.at(-1)||""];let cx=x0;basics.forEach((value,i)=>{ctx.strokeRect(cx,y0+rowH*(row+1),widths[i],rowH);ctx.font=i===2?"bold 20px sans-serif":"18px sans-serif";ctx.textAlign=i===2?"left":"center";ctx.fillText(String(value),cx+(i===2?8:widths[i]/2),y0+rowH*(row+1)+41);cx+=widths[i];});const pas=state.plateAppearances[side][row]||[];for(let i=0;i<9;i++){const info=symbolInfo(pas[i]);const cy=y0+rowH*(row+1);ctx.strokeRect(cx,cy,widths[i+4],rowH);if(pas[i])drawSymbol(ctx,cx,cy,widths[i+4],rowH,info);cx+=widths[i+4];}});
  }
  function drawSymbol(ctx,x,y,w,h,info){const cx=x+w/2,cy=y+h/2+2,r=21,pts=[[cx,cy+r],[cx+r,cy],[cx,cy-r],[cx-r,cy],[cx,cy+r]];ctx.strokeStyle="#77857d";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<5;i++)ctx.lineTo(pts[i][0],pts[i][1]);ctx.stroke();ctx.strokeStyle="#d32626";ctx.lineWidth=3;for(let i=0;i<Math.min(4,info.advance);i++){ctx.beginPath();ctx.moveTo(...pts[i]);ctx.lineTo(...pts[i+1]);ctx.stroke();}ctx.fillStyle="#17211c";ctx.font="bold 15px sans-serif";ctx.textAlign="center";ctx.fillText(info.mark,cx,cy+5);ctx.font="12px sans-serif";ctx.fillText(info.out,cx,cy+19);ctx.font="10px sans-serif";ctx.textAlign="left";ctx.fillText(info.pitches.join(""),x+3,y+11);if(info.run){ctx.strokeStyle="#d32626";ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,16,0,Math.PI*2);ctx.stroke();}}
  async function exportImage(){const state=window.ScorebookGame?.snapshot();if(!state)return;const canvas=document.createElement("canvas");drawExport(canvas,state);canvas.toBlob(async blob=>{if(!blob)return;const name=`scorebook-${side===0?"away":"home"}-${new Date().toISOString().slice(0,10)}.jpg`;const file=new File([blob],name,{type:"image/jpeg"});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"試合スコアブック"});return;}}catch(error){if(error.name==="AbortError")return;}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},"image/jpeg",.92);}
  function open(){side=0;buildSheet();$("#scorebookView").hidden=false;document.body.classList.add("panel-open");screen.orientation?.lock?.("landscape").catch(()=>{});}
  function close(){$("#scorebookView").hidden=true;document.body.classList.remove("panel-open");screen.orientation?.unlock?.();}
  function setup(){$("#openScorebook").onclick=open;$("#closeScorebook").onclick=close;$("#toggleScorebookSide").onclick=()=>{side=side?0:1;buildSheet();};$("#exportScorebook").onclick=exportImage;}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",setup):setup();
})();
