(() => {
  "use strict";
  const $ = q => document.querySelector(q);
  const esc = value => { const e=document.createElement("span");e.textContent=value??"";return e.innerHTML; };
  let side = 0;
  const positionLabel = value => value || "－";
  function inningRuns(state, team, inning){return (state.runEvents||[]).filter(run=>run.inning===inning&&((run.half==="top"?0:1)===team)).length;}
  function symbolInfo(pa){
    if(!pa)return {mark:"",advance:0,pitches:[],out:""};
    const s=pa.score||{};const result=s.result||pa.text||"";const fielders=s.fielders||[];const seq=fielders.join("-");let mark="",advance=0;
    const batted=({ゴロ:"∪",ライナー:"－",フライ:"∩",バント:"BT"})[s.contact]||"";
    if(result==="四球"){mark="B";advance=1;}else if(result==="死球"){mark="DB";advance=1;}else if(result==="strikeout"||result==="三振"){mark="K";}else if(result==="振り逃げ"){mark="ꓘ";advance=(s.decisions||[]).some(d=>d.runner==="batter"&&d.result==="SAFE")?1:0;}else if(result==="単打"){mark=`${fielders[0]||""}${batted||"∪"}`;advance=1;}else if(result==="二塁打"){mark=`${fielders[0]||""}${batted||"－"}②`;advance=2;}else if(result==="三塁打"){mark=`${fielders[0]||""}${batted||"－"}③`;advance=3;}else if(result==="本塁打"){mark=`${fielders[0]||""}${batted||"∩"}HR`;advance=4;}else if(result==="野選"){mark=`FC ${seq}`;advance=1;}else if(/エラー/.test(result)){mark=`${fielders.at(-1)||fielders[0]||""}E`;advance=1;}else if(result==="犠打"){mark=`◇${seq||"BT"}`;}else if(result==="犠飛"){mark=`◇${fielders[0]||""}∩`;}else if(result==="バントアウト"){mark=`BT ${seq}`;}else if(result==="catch"){mark=`${fielders[0]||""}${s.contact==="ライナー"?"－":"∩"}`;}else if(seq){mark=`${seq}${batted}`;}else{
      const old=String(pa.text||"");if(old==="三振")mark="K";else if(old==="四球"){mark="B";advance=1;}else if(old==="死球"){mark="DB";advance=1;}else if(/本$/.test(old)){mark="HR";advance=4;}else if(/3$/.test(old)){mark="③";advance=3;}else if(/2$/.test(old)){mark="②";advance=2;}else if(/安$/.test(old)){mark="∪";advance=1;}else if(/失$/.test(old)){mark="E";advance=1;}else if(/野選$/.test(old)){mark="FC";advance=1;}else if(/直$/.test(old))mark="－";else if(/飛$/.test(old))mark="∩";else mark=old;
    }
    const trajectory=mark.includes("∪")?"∪":mark.includes("∩")?"∩":mark.includes("－")?"－":"";if(trajectory)mark=mark.replaceAll(trajectory,"");
    const later=s.advances||[];if(later.length)advance=Math.max(advance,...later.map(a=>a.to===0?4:a.to));
    const finalOut=s.finalOutNumber||s.outNumber;const center=s.final==="run"?"○":s.final==="left"?"ℓ":({1:"Ⅰ",2:"Ⅱ",3:"Ⅲ"})[finalOut]||"";
    return {mark,trajectory,advance,pitches:s.pitches||[],out:center,run:s.final==="run",later};
  }
  function symbolCell(pa){const info=symbolInfo(pa);const pts=[[50,60],[72,35],[50,10],[28,35],[50,60]];const lines=Array.from({length:Math.min(4,info.advance)},(_,i)=>`<line x1="${pts[i][0]}" y1="${pts[i][1]}" x2="${pts[i+1][0]}" y2="${pts[i+1][1]}"/>`).join("");const positions={"1-2":[80,21],"2-3":[35,18],"3-0":[24,55]};const later=(info.later||[]).map(a=>{const p=positions[`${a.from}-${a.to}`]||[50,35];return `<text class="advance-mark" x="${p[0]}" y="${p[1]}">${esc(a.mark)}</text>`}).join("");const pitches=info.pitches.map((p,i)=>`<tspan x="6" y="${11+i*9}">${esc(p)}</tspan>`).join("");const ground=info.trajectory==="∪";return `<svg class="score-symbol" viewBox="0 0 90 70" role="img" aria-label="${esc(pa?.text||info.mark||"未記入")}"><g class="cell-guides"><line x1="14" y1="0" x2="14" y2="70"/><path d="M50 10 L72 35 L50 60 L28 35 Z"/><line x1="50" y1="0" x2="50" y2="10"/><line x1="72" y1="35" x2="90" y2="35"/><line x1="50" y1="60" x2="50" y2="70"/><line x1="14" y1="35" x2="28" y2="35"/></g><g class="advance ${info.advance?"reached":""}">${lines}</g>${later}<text class="pitch-seq">${pitches}</text><text class="pitch-total" x="6" y="67">${info.pitches.length||""}</text><text class="trajectory" x="76" y="${ground?68:48}">${esc(info.trajectory)}</text><text class="play-mark" x="76" y="${ground?57:65}">${esc(info.mark)}</text><text class="out-mark" x="50" y="41">${esc(info.out)}</text></svg>`;}
  function slotPlayerIds(slot){const ids=[];const add=id=>{if(id&&!ids.includes(id))ids.push(id);};(slot.history||[]).forEach(h=>{add(h.playerId);add(h.outgoingPlayerId);add(h.incomingPlayerId);});add(slot.currentPlayerId);return ids;}
  function slotPlayerEntries(state,slot){return slotPlayerIds(slot).map(id=>{const player=state.players.find(p=>p.id===id)||{canonicalName:id};const appearance=[...(state.appearances||[])].reverse().find(a=>a.playerId===id);const change=(slot.history||[]).find(h=>h.incomingPlayerId===id);const marker=change?.type==="pinchHitter"?"H":change?.type==="pinchRunner"?"R":"";return {player,position:marker||appearance?.defensiveNumber||appearance?.defensivePositions?.at(-1)||""};});}
  function buildSheet(){
    const state=window.ScorebookGame?.snapshot();if(!state)return;
    const team=state.teams[side]||{name:side?"後攻":"先攻"};const opponent=state.teams[1-side]||{};
    const innings=Math.max(9,state.inning||1);const inningHeaders=Array.from({length:innings},(_,i)=>`<th>${i+1}</th>`).join("");
    const scoreRows=[0,1].map(teamIndex=>`<tr><th>${esc(state.teams[teamIndex]?.name||["先攻","後攻"][teamIndex])}</th>${Array.from({length:innings},(_,i)=>`<td>${inningRuns(state,teamIndex,i+1)||""}</td>`).join("")}<td class="total">${state.scores[teamIndex]}</td></tr>`).join("");
    const rows=state.lineupSlots[side].map((slot,i)=>{const entries=slotPlayerEntries(state,slot);const pa=state.plateAppearances[side][i]||[];const legacy=pa.length>0&&pa.every(p=>!p.score?.inning);const inningCells=Array.from({length:innings},(_,j)=>{const events=legacy?(pa[j]?[pa[j]]:[]):pa.filter(p=>p.score?.inning===j+1);return `<td class="pa">${(events.length?events:[null]).map(symbolCell).join("")}</td>`;}).join("");return `<tr><th>${i+1}</th><td><div class="player-stack">${entries.map(e=>`<span>${esc(e.player.uniformNumber||"")}</span>`).join("")}</div></td><td class="player"><div class="player-stack">${entries.map(e=>`<span>${esc(e.player.canonicalName||"")}</span>`).join("")}</div></td><td><div class="player-stack">${entries.map(e=>`<span>${esc(positionLabel(e.position))}</span>`).join("")}</div></td>${inningCells}</tr>`;}).join("");
    $("#scorebookSideLabel").textContent=side===0?"先攻":"後攻";$("#toggleScorebookSide").textContent=side===0?"後攻へ":"先攻へ";
    $("#scorebookSheet").innerHTML=`<div class="scorebook-title"><span>${esc(team.name)}</span><h2>試合スコアブック</h2><span class="score">${state.scores[0]} － ${state.scores[1]}</span></div><table class="score-line"><thead><tr><th>チーム</th>${inningHeaders}<th>計</th></tr></thead><tbody>${scoreRows}</tbody></table><table class="score-grid"><thead><tr><th>打順</th><th>背番号</th><th>選手名</th><th>守備</th>${Array.from({length:innings},(_,i)=>`<th>${i+1}回</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><p class="scorebook-note">表示：${esc(team.name)}　対戦：${esc(opponent.name||"")}　最終更新：${new Date().toLocaleString("ja-JP")}</p>`;
  }
  function drawExport(canvas,state){
    const ctx=canvas.getContext("2d");const W=1600,H=900;canvas.width=W;canvas.height=H;ctx.fillStyle="#fff";ctx.fillRect(0,0,W,H);ctx.fillStyle="#173424";ctx.font="bold 34px sans-serif";ctx.textAlign="center";ctx.fillText("試合スコアブック",W/2,48);ctx.font="bold 25px sans-serif";ctx.textAlign="left";ctx.fillText(state.teams[side]?.name||["先攻","後攻"][side],40,88);ctx.textAlign="right";ctx.fillText(`${state.scores[0]} － ${state.scores[1]}`,W-40,88);
    const x0=35,y0=115,rowH=68,widths=[60,80,210,80,...Array(9).fill(124)];const headers=["打順","背番号","選手名","守備",...Array.from({length:9},(_,i)=>`打席${i+1}`)];ctx.strokeStyle="#20382b";ctx.lineWidth=2;ctx.font="bold 18px sans-serif";ctx.textAlign="center";let x=x0;headers.forEach((h,i)=>{ctx.strokeRect(x,y0,widths[i],rowH);ctx.fillText(h,x+widths[i]/2,y0+41);x+=widths[i];});
    state.lineupSlots[side].forEach((slot,row)=>{const entries=slotPlayerEntries(state,slot);const basics=[row+1,entries.map(e=>e.player.uniformNumber||"").join("/"),entries.map(e=>e.player.canonicalName||"").join(" / "),entries.map(e=>e.position||"").join("/")];let cx=x0;basics.forEach((value,i)=>{ctx.strokeRect(cx,y0+rowH*(row+1),widths[i],rowH);ctx.font=i===2?"bold 16px sans-serif":"16px sans-serif";ctx.textAlign=i===2?"left":"center";ctx.fillText(String(value),cx+(i===2?8:widths[i]/2),y0+rowH*(row+1)+41);cx+=widths[i];});const pas=state.plateAppearances[side][row]||[];const legacy=pas.length>0&&pas.every(p=>!p.score?.inning);for(let i=0;i<9;i++){const pa=legacy?pas[i]:pas.find(p=>p.score?.inning===i+1);const info=symbolInfo(pa);const cy=y0+rowH*(row+1);ctx.strokeRect(cx,cy,widths[i+4],rowH);drawSymbol(ctx,cx,cy,widths[i+4],rowH,info);cx+=widths[i+4];}});
  }
  function drawSymbol(ctx,x,y,w,h,info){const left=x+18,cx=x+w*.55,cy=y+h/2,r=20,pts=[[cx,cy+r],[cx+r,cy],[cx,cy-r],[cx-r,cy],[cx,cy+r]];ctx.save();ctx.strokeStyle="#9ab7a6";ctx.lineWidth=1;ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left,y+h);ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<5;i++)ctx.lineTo(pts[i][0],pts[i][1]);ctx.moveTo(cx,y);ctx.lineTo(cx,cy-r);ctx.moveTo(cx+r,cy);ctx.lineTo(x+w,cy);ctx.moveTo(cx,cy+r);ctx.lineTo(cx,y+h);ctx.moveTo(left,cy);ctx.lineTo(cx-r,cy);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle="#d32626";ctx.lineWidth=3;for(let i=0;i<Math.min(4,info.advance);i++){ctx.beginPath();ctx.moveTo(...pts[i]);ctx.lineTo(...pts[i+1]);ctx.stroke();}const mx=x+w-20,ground=info.trajectory==="∪";ctx.fillStyle="#17211c";ctx.font="bold 18px sans-serif";ctx.textAlign="center";ctx.fillText(info.mark,mx,y+h-(ground?15:4));ctx.font="bold 17px sans-serif";ctx.fillText(info.trajectory,mx,y+h-(ground?1:22));ctx.font="bold 12px sans-serif";(info.later||[]).forEach(a=>{const p={"1-2":[x+w-12,y+20],"2-3":[cx-20,y+17],"3-0":[cx-25,y+h-10]}[`${a.from}-${a.to}`];if(p)ctx.fillText(a.mark,p[0],p[1]);});ctx.font="bold 19px serif";ctx.fillText(info.out,cx,cy+6);ctx.font="10px sans-serif";info.pitches.forEach((p,i)=>ctx.fillText(p,x+9,y+11+i*9));if(info.pitches.length)ctx.fillText(String(info.pitches.length),x+9,y+h-3);ctx.restore();}
  async function exportImage(){const state=window.ScorebookGame?.snapshot();if(!state)return;const canvas=document.createElement("canvas");drawExport(canvas,state);canvas.toBlob(async blob=>{if(!blob)return;const name=`scorebook-${side===0?"away":"home"}-${new Date().toISOString().slice(0,10)}.jpg`;const file=new File([blob],name,{type:"image/jpeg"});try{if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"試合スコアブック"});return;}}catch(error){if(error.name==="AbortError")return;}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},"image/jpeg",.92);}
  function open(){side=0;buildSheet();$("#scorebookView").hidden=false;document.body.classList.add("panel-open");screen.orientation?.lock?.("landscape").catch(()=>{});}
  function close(){$("#scorebookView").hidden=true;document.body.classList.remove("panel-open");screen.orientation?.unlock?.();}
  function setup(){$("#openScorebook").onclick=open;$("#closeScorebook").onclick=close;$("#toggleScorebookSide").onclick=()=>{side=side?0:1;buildSheet();};$("#exportScorebook").onclick=exportImage;}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",setup):setup();
})();
